# Experiment Configuration

# Model settings
model:
  name: VGG16  # Options: VGG16, Resnet18
  num_classes: 2

# Optimizer settings
optimizer:
  name: Adam  # Options: Adam, SGD
  lr: 1e-3

# Training settings
training:
  epochs: 100
  batch_size: 64

# Data settings
data:
  image_size: 64
  augment: true
  validation_split: 0
